# Generated by Django 2.1.2 on 2018-11-01 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numarasi', models.CharField(max_length=16)),
                ('tarih', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.IntegerField()),
                ('ozellik', models.TextField()),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envanter_takip.Fatura')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envanter_takip.Kategori')),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envanter_takip.Marka')),
            ],
        ),
        migrations.CreateModel(
            name='Zimmet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=255)),
                ('teslim_tarihi', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='urun',
            name='zimmet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envanter_takip.Zimmet'),
        ),
    ]
