# Generated by Django 2.1.3 on 2018-12-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envanter_takip', '0002_auto_20181125_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fatura',
            old_name='numarasi',
            new_name='numara',
        ),
    ]
